### ISSUE TITLE
Hang during the --sql-file migrations in 0.10.0-beta.3

### ISSUE THREAD

**Issue by Nedudi** [db-migrate/node-db-migrate#319]
1) create sql migration with  --sql-file
2) 

insert any simple sql like 

    select * from users;

in ...migration-up.sql file

3)

    db-migrate up

----

*result:*

console hang, there is no record in `migrations` table

same working on the rignt way in 0.9.23 version

---

thanks in advance

**Comment by wzrdtales** [comment]
Thank you for reporting, the new template sreleased in beta.4 should work again.

**Comment by Nedudi** [comment]
thanks a lot

after update I have 


~/work/kuku/login • db-migrate create first-test-migration77
dima@Dmitrys-MacBook-Pro
module.js:338
    throw err;
          ^
Error: Cannot find module 'when'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dima/work/kuku/login/node_modules/db-migrate/node_modules/final-fs/index.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by Nedudi** [comment]
opps.. sorry

reinstalled and all is great now !!

Awesome!
