### ISSUE TITLE
db.insert is not a function

### ISSUE THREAD

**Issue by ryanrolds** [db-migrate/node-db-migrate#542]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior
`[ERROR] TypeError: db.insert is not a function`

## Expected behavior
The insert function to exist

## Minimal reproduction of the problem with instructions
Create a migration and use the db.insert function with 0.10.3

## What is the motivation / use case for changing the behavior?
It works in 0.10.2 and a removing a function should be a major version rev.

## Environment
Ubuntu 14.04 and Ubuntu 16.04 w/ Postgres 9.6

<pre><code>
db-migrate version: 0.10.3
db-migrate-pg version: 0.2.5 (tried with 0.3.0 and had same issue).

Additional information:
- Node version: 6.11.5
- Platform:  Linux
</code></pre>

**Comment by wzrdtales** [comment]
Thanks for reporting, we removed the deprecation notice on insert for the time being.

Released fix under:
+ db-migrate@0.10.5

**Comment by ryanrolds** [comment]
Thanks. I think I was one of the people urging for the removal of the deprecation notice ^_^.

You're guys are doing a good job, shi... stuff happens.
